---

- name: Add an helm apt signing key
  ansible.builtin.apt_key:
    url: https://baltocdn.com/helm/signing.asc
    keyring: /usr/share/keyrings/helm.gpg
    state: present

- name: Add helm deb
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main"
    filename: helm
    state: present

- name: Install helm
  ansible.builtin.package:
    name: helm
    state: present
    update_cache: true