---
- name: add an apt signing key to a specific keyring file
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /usr/share/keyrings/microsoft-archive-keyring.gpg

- name: add vscode repo
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64,arm64,armhf signed-by=/usr/share/keyrings/microsoft-archive-keyring.gpg] https://packages.microsoft.com/repos/code stable main
    filename: vscode
    state: present

- name: installion vscode
  ansible.builtin.package:
    name: code
    state: present
    update_cache: true
