---
- name: add an apt signing key to a specific keyring file
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /usr/share/keyrings/microsoft-archive-keyring.gpg

- name: add repo
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-archive-keyring.gpg] https://packages.microsoft.com/repos/ms-teams stable main
    filename: teams
    state: present

- name: installion
  ansible.builtin.package:
    name: teams
    state: present
    update_cache: true
