---

- name: Download file with check (md5)
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-{{ ansible_architecture }}
    dest: /usr/local/bin/docker-compose
    checksum: md5:8f68ae5d2334eecb0ee50b809b5cec58

# docker-compose binary executable permissions
- name: Set executable permissions
  ansible.builtin.file:
    path: /usr/local/bin/docker-compose
    state: file
    mode: '0755'

- name: Create a symbolic link
  ansible.builtin.file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    state: link

