---
# - name: Download virtualbox deb
#   ansible.builtin.apt_repository:
#     repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib
#     state: present
#     filename: virtualbox

- name: Install a .deb package from the internet
  apt:
    deb: https://download.virtualbox.org/virtualbox/6.1.32/virtualbox-6.1_6.1.32-149290~Ubuntu~eoan_amd64.deb
    # deb: https://download.virtualbox.org/virtualbox/5.2.28/virtualbox-5.2_5.2.28-130011~Ubuntu~bionic_amd64.deb