---
- name: Install common fundamental packages
  ansible.builtin.package:
    name:
      - curl
      - gnupg
      - ca-certificates
    state: latest
    update_cache: true

- name: create keyring directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    recurse: yes
    
- name: add an apt signing key to a specific keyring file
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg

- name: add repo
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    filename: docker
    state: present

- name: install docker packages
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: add the user {{ ansible_user }}, appending the group 'docker'
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
    state: present
